name: Daily MA60 Scan

permissions:
  contents: write

on:
  schedule:
    # 每个交易日收盘后 20:10 UTC 运行（UTC 固定；JST 次日 05:10 左右）
    - cron: "10 20 * * 1-5"
  workflow_dispatch: {}   # 允许你手动点运行

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run scan
        env:
          USE_SP500: "true"                # 开/关 S&P 500 自动名单
          FINNHUB_TOKEN: ${{ secrets.FINNHUB_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TICKERS: ${{ secrets.TICKERS }}
        run: python scan.py
        
      - name: Commit subscriber updates
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "Update subscribers & offset [skip ci]" || true
            git push
          fi
